### PR TITLE
Fix Gift Cards

### LINKED ISSUE #3222: Gift card permissions issue
### Description of the issue
Users with gift card permission can not get to gift card pages

### Steps to reproduce the problem

1. Create a user with Manage gift cards permission
2. Log in to the dashboard
3. Enter products -> gift cards

### Expected Result
Users able to interact with gift cards
…

### Actual Result
Error id: 52b4bb6b1ce14180a2ae35a752621dcb
Zrzut ekranu 2023-02-27 o 12 27 32

```
query GiftCardProductsCount {
  giftCardProductTypes: productTypes(filter: {kind: GIFT_CARD}) {
    totalCount
    __typename
  }
  giftCardProducts: products(filter: {giftCard: true}) {
    totalCount
    __typename
  }
}

{
  "PERMISSION_MANAGE_USERS": false,
  "PERMISSION_MANAGE_STAFF": false,
  "PERMISSION_IMPERSONATE_USER": false,
  "PERMISSION_MANAGE_APPS": false,
  "PERMISSION_MANAGE_OBSERVABILITY": false,
  "PERMISSION_MANAGE_CHECKOUTS": false,
  "PERMISSION_HANDLE_CHECKOUTS": false,
  "PERMISSION_HANDLE_TAXES": false,
  "PERMISSION_MANAGE_TAXES": false,
  "PERMISSION_MANAGE_CHANNELS": false,
  "PERMISSION_MANAGE_DISCOUNTS": false,
  "PERMISSION_MANAGE_GIFT_CARD": true,
  "PERMISSION_MANAGE_MENUS": false,
  "PERMISSION_MANAGE_ORDERS": false,
  "PERMISSION_MANAGE_PAGES": false,
  "PERMISSION_MANAGE_PAGE_TYPES_AND_ATTRIBUTES": false,
  "PERMISSION_HANDLE_PAYMENTS": true,
  "PERMISSION_MANAGE_PLUGINS": false,
  "PERMISSION_MANAGE_PRODUCTS": false,
  "PERMISSION_MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES": false,
  "PERMISSION_MANAGE_SHIPPING": false,
  "PERMISSION_MANAGE_SETTINGS": false,
  "PERMISSION_MANAGE_TRANSLATIONS": false
}

response:
{
  "errors": [
    {
      "message": "More than one channel exists. Specify which channel to use.",
      "locations": [
        {
          "line": 6,
          "column": 3
        }
      ],
      "path": [
        "giftCardProducts"
      ],
      "extensions": {
        "exception": {
          "code": "GraphQLError"
        }
      }
    }
  ],
  "data": {
    "giftCardProductTypes": {
      "totalCount": 2,
      "__typename": "ProductTypeCountableConnection"
    },
    "giftCardProducts": null
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 2,
      "maximumAvailable": 50000
    }
  }
}
```

### System information

Dashboard version:

`v3.11 v.3.10`

Core version:

`v?.?.?`

Operating system:

- [ ] MacOS

Browser:

- [ ] Chrome

### PR DESCRIPTION
**Pull request by krzysztofzuraw**
I want to merge this change because it fixes #3222.

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

### CODE REVIEW

File: src/giftCards/GiftCardsList/GiftCardListSearchAndFilters/GiftCardListSearchAndFilters.tsx [hunk 1]
```diff
@@ -39,14 +40,12 @@ import {
 const GiftCardListSearchAndFilters: React.FC = () => {
   const navigate = useNavigator();
   const intl = useIntl();
+  const [selectedChannel] = useLocalStorage("channel", "");
```
Comment (Droniu) [inline src/giftCards/GiftCardsList/GiftCardListSearchAndFilters/GiftCardListSearchAndFilters.tsx:43]: **question:** Is this local setting? If so, it might be better to use more descriptive key, e.g. `giftCardChannel`. If this is global then it's okay as it is.

**Review by Droniu — APPROVED** [review]

File: src/giftCards/GiftCardsList/GiftCardListSearchAndFilters/GiftCardListSearchAndFilters.tsx (hunk 1 above)
Comment (krzysztofzuraw) [reply src/giftCards/GiftCardsList/GiftCardListSearchAndFilters/GiftCardListSearchAndFilters.tsx:43]: it is global - currently selected channel from home page 😄

**Comment by szczecha** [comment]
Entering the gift page works but if the user wants to go to gift card details he sees an unexpected error once again even if gift card data are fetched and he created this card.

https://user-images.githubusercontent.com/30683248/225831183-ce2e1d94-93a5-4f87-8364-f2d2596477e0.mov

**Comment by krzysztofzuraw** [comment]
@szczecha as we discussed with @wojteknowacki and @andrzejewsky we need a better way of creating and assigning permissions to the users of the dashboard - but this issue is out of the scope of this ticket 😄

**Review by szczecha — APPROVED** [review]
