### PR TITLE
Do not send availableForPurchaseDate if channel is unavailable

### LINKED ISSUE #2474: Unable to set product to 'Unavailable for purchase'
### What I'm trying to achieve

…

### Steps to reproduce the problem

1. Create a new product, 
2. Save
3. Selct channel on Availability secion 
4. Reload page
5. Try to change availability in the channel to 'Unavailable for purchase'
6. Save 

Result: error is shown to the user 

### Screenshots

https://user-images.githubusercontent.com/30683248/198048910-fdabae4f-5a78-40ec-9776-e5d1e6965702.mov

### HTTP request and response from inspector

mutation ProductChannelListingUpdate
vars:
```
{
  "id": "UHJvZHVjdDoxMzkx",
  "input": {
    "removeChannels": [],
    "updateChannels": [
      {
        "availableForPurchaseDate": "2022-10-26",
        "channelId": "Q2hhbm5lbDoyMjQz",
        "isAvailableForPurchase": false,
        "isPublished": false,
        "publicationDate": "2022-10-26",
        "visibleInListings": false
      }
    ]
  }
}
```

Response
```
{
  "data": {
    "productChannelListingUpdate": {
      "errors": [
        {
          "code": "INVALID",
          "field": "availableForPurchaseDate",
          "message": "Cannot set available for purchase date when isAvailableForPurchase is false.",
          "channels": [
            "Q2hhbm5lbDoyMjQz"
          ],
          "__typename": "ProductChannelListingError"
        }
      ],
      "__typename": "ProductChannelListingUpdate"
    }
  }
}
```

### System information

Dashboard version:
`dashboard v3.8.0-dev`

Core version:
`core v3.8.0-a`

Operating system:

- [ ] Windows
- [ ] Linux
- [ x] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ x] Chrome
- [ ] Edge
- [ ] Other

### PR DESCRIPTION
**Pull request by krzysztofzuraw**
I want to merge this change because it fixes #2474. Previously we send `availableForPurchaseDate` no matter of availability of the channel. I changed that and currently it will be based on `isAvailableForPurchase` boolean. I also fixed a rules of hooks error.

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://apps.saleor.io
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?
To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants

CONTAINERS=1

### CODE REVIEW

**Review by orzechdev — APPROVED** [review]

File: src/products/components/ProductUpdatePage/formChannels.ts [hunk 1]
```diff
@@ -40,18 +40,27 @@ export function useProductChannelListingsForm(
...
+                ...data,
+                availableForPurchaseDate: data.isAvailableForPurchase
+                  ? data.availableForPurchase
+                  : null,
+              }
+            : prevListing,
+        ),
+      }));
+      triggerChange();
+      touch(id);
```
Comment (andrzejewsky) [inline src/products/components/ProductUpdatePage/formChannels.ts:60]: could you somehow organize it in separate functions so it can be more readable?

**Review by andrzejewsky — CHANGES_REQUESTED** [review]

File: src/products/components/ProductUpdatePage/formChannels.ts (hunk 1 above)
Comment (krzysztofzuraw) [reply src/products/components/ProductUpdatePage/formChannels.ts]: Done - please check 😊

**Review by andrzejewsky — APPROVED** [review]

**Review by orzechdev — APPROVED** [review]

**Review by szczecha — APPROVED** [review]

**Comment by krzysztofzuraw** [comment]
@timuric can you please take a look?
