### PR TITLE
Fix strict null checks in warehouses

### LINKED ISSUE #2934: Fix strict null checks in warehouses

### PR DESCRIPTION
**Pull request by Droniu**
Closes #2934.
I want to merge this change because: 
- it fixes strict null errors in warehouses,
- it adds better labels in settings card in warehouse details view.

Views affected for QA testing:
- Warehouse create
- Warehouse details
- Warehouse list

**PR intended to be tested with API branch:**  3.10-dev

### Screenshots
Before:
image
After:
image

### Pull Request Checklist

1. [x] This code contains UI changes
2. [x] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [x] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://apps.saleor.io
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?
To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

### CODE REVIEW

File: src/utils/limits.ts [hunk 1]
```diff
@@ -10,14 +10,23 @@ export function hasLimits(
 
   return limits.allowedUsage[key] !== null;
 }
-
+/**
+ * Returns false when query is in the loading state.
+ * */
```
Comment (poulch) [inline src/utils/limits.ts:15]: Function check if limit is reach, imo this description is incorrect

**Review by poulch — DISMISSED** [review]

**Review by andrzejewsky — APPROVED** [review]

**Review by andrzejewsky — DISMISSED** [review]

**Review by andrzejewsky — APPROVED** [review]

**Review by poulch — APPROVED** [review]

**Review by karolm-saleor — APPROVED** [review]
✓ QA Passed
