### PR TITLE
Fix allow click on webhook checkbox

### LINKED ISSUE #3317: Webhooks details - async events selection should be possible by click entire row
Expected behavior : whole row should be clickable

https://user-images.githubusercontent.com/124166231/224053014-b14827ec-0c67-4c3d-8ceb-aacb96266b6a.mov

### PR DESCRIPTION
**Pull request by krzysztofzuraw**
I want to merge this change because it fixes #3317 

**PR intended to be tested with API branch:** 

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

### CODE REVIEW

File: src/custom-apps/components/WebhookEvents/WebhookEvents.tsx [hunk 1]
```diff
@@ -158,22 +158,31 @@ const WebhookEvents: React.FC<WebhookEventsProps> = ({
...
-                          className={classes.checkbox}
-                        />
+                    <ListItem className={classes.eventListItem} key={idx}>
+                      <ListItemCell className={classes.eventListItemCell}>
+                        <label
+                          htmlFor={`event-checkbox-${idx}`}
+                          className={classes.eventListLabel}
+                          style={{
+                            gridTemplateColumns: `1fr ${checkbox}`,
+                          }}
```
Comment (poulch) [inline src/custom-apps/components/WebhookEvents/WebhookEvents.tsx:168]: question: Could you put those styles into `classes.eventListLabel`

**Review by poulch — APPROVED** [review]

File: src/custom-apps/components/WebhookEvents/WebhookEvents.tsx (hunk 1 above)
Comment (krzysztofzuraw) [reply src/custom-apps/components/WebhookEvents/WebhookEvents.tsx:168]: let me check if I can pass it to JSS as prop 🤔

**Review by poulch — DISMISSED** [review]

**Review by Droniu — DISMISSED** [review]

**Comment by wojteknowacki** [comment]
Looks like hover effect on dark mode issue - when hover checkobx shadow blinks next to it
https://user-images.githubusercontent.com/124166231/224638414-b3161803-7261-4fe2-afc2-d08ea96acd74.mov

**Review by Droniu — APPROVED** [review]

**Review by poulch — APPROVED** [review]
